/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.sdu.portal.connector;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
